version: "3.8"
services:
  db:
    image: mysql:latest
    ports:
      - 3000:3000
    command: --init-file /data/application/init.sql
    volumes:  # run init script in the container path
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: db_example
      MYSQL_USER: springuser  # user connected by spring
      MYSQL_PASSWORD: ThePassword
  mail:
    image: maildev/maildev
    ports:
      - 1080:1080